name: 'kubernetes-deploy-pilot'
author: 'jonathan.duval@cheerz'
description: 'An action to control and apply deployment on k8s cluster based on istio virtual service.'
branding:
  icon: 'upload'
  color: 'blue'
inputs:
  version-to-deploy: 
    description: 'The new version release you want to deploy'
    required: true
  application-name:
    description: 'the name of the application you want to deploy'
    required: true
  action:
    description: 'Deploy action to apply (create|complete|update|cancel)'
    required: false
  namespace:
    description: 'Namespace of the application'
    required: false
    default: "staging"
  applicationValuePath:
    description: 'Path of application value file'
    required: false
    default: "manifest/application-value.yml"
  networkValuePath:
    description: 'Path of network value file'
    required: false
    default: "manifest/network-value.yml" 
  workerValuePath:
    description: 'Path of worker value file'
    required: false
    default: "" 
  cronJobsValuePath:
    description: 'Path of cron jobs value file'
    required: false
    default: ""
  useApplicationVersionForImageTag:
    description: 'Do we use the new application version to set the docker image tag'
    required: false
    default: "false" 
  ApplicationChartVersion:
    description: 'Version to use for application chart'
    required: false
    default: "latest"
  networkChartVersion:
    description: 'Version to use for network chart'
    required: false
    default: "latest"
  workerChartVersion:
    description: 'Version to use for worker chart'
    required: false
    default: "latest"
  cronJobsChartVersion:
    description: 'Version to use for cron jobs chart'
    required: false
    default: "latest"
  github-id:
    description: 'Application github repo id'
    required: false
    default: "0"
  github-path:
    description: 'Application github repo path'
    required: false
    default: "/"
  github-url:
    description: 'Application github repo url'
    required: false
    default: "https://github.com"
outputs:
  new-version: 
    description: "Return the new version number deployed"
    value: ${{ steps.main.outputs.new-version}}
  actual-version: 
    description: "Previous running version or v0.0.0 in case of new deployment OR equal to new-version in case of complete deployment"
    value: ${{ steps.main.outputs.actual-version}}
runs:
  using: "composite"
  steps: 
    - id: main
      env: 
        BASE_WORKING_PATH: "${{ github.workspace }}"
      run: |
        ${{ github.action_path }}/main.sh \
        --application-image-tag="${{ inputs.useApplicationVersionForImageTag }}" \
        --action="${{ inputs.action }}" \
        --namespace="${{ inputs.namespace }}" \
        --version-deploy="${{ inputs.version-to-deploy }}" \
        --app-value-path="${{ inputs.applicationValuePath }}" \
        --network-value-path="${{ inputs.networkValuePath }}" \
        --worker-value-path="${{ inputs.workerValuePath }}" \
        --cron-jobs-value-path="${{ inputs.cronJobsValuePath }}" \
        --app-chart-version="${{ inputs.ApplicationChartVersion }}" \
        --network-chart-version="${{ inputs.networkChartVersion }}" \
        --worker-chart-version="${{ inputs.workerChartVersion }}" \
        --cron-jobs-chart-version="${{ inputs.cronJobsChartVersion }}" \
        --github-id="${{ inputs.github-id }}" \
        --github-path="${{ inputs.github-path }}" \
        --github-url="${{ inputs.github-url }}" \
        ${{ inputs.application-name }}
      shell: bash
    